import React from 'react';
import { useFarmProject } from '../../context/FarmProjectContext';
import { calculateFinancialMetrics, formatNaira } from '../../utils/calculations';
import { useCalculator } from '../../hooks/useCalculator';

export const CashFlowView: React.FC = () => {
  const { currentProject, userProfile } = useFarmProject();
  const metrics = calculateFinancialMetrics(currentProject);
  const signInDate = new Date(userProfile.signedInAt || Date.now());
  const cashFlowStartDate = `${signInDate.getFullYear()}-${String(signInDate.getMonth() + 1).padStart(2, '0')}-01`;
  const projection = useCalculator('cashflow', { project: { financialModel: currentProject.financialModel, productionPlan: currentProject.productionPlan, marketPlan: currentProject.marketPlan, farmDetails: { expectedStartDate: cashFlowStartDate } } });
  const months = (((projection.result?.months as { monthName: string; monthIndex: number; year?: number; periodLabel?: string; revenue: number; expenses: number; netCashFlow: number; cumulativeCashFlow: number; harvest: boolean }[] | undefined) ?? [])).slice().sort((a, b) => a.monthIndex - b.monthIndex);
  const roi = currentProject.toolAnalysis?.roi;
  const flows = roi?.cumulativeCashFlows as { period: number; netCashFlow: number; cumulativeCashFlow: number }[] | undefined;
  return <div className="max-w-7xl mx-auto space-y-6">
    <header><h2 className="text-2xl font-bold text-neutral-900">Cash Flow</h2><p className="text-sm text-neutral-500 mt-1">Calendar months begin with the month you entered the workspace. Annual operating costs are spread evenly; Month 1 includes startup capital, including working capital, and scheduled loan repayments.</p></header>
    <div className="grid sm:grid-cols-3 gap-4"><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-neutral-500">Expected annual revenue</p><p className="text-xl font-bold mt-1">{formatNaira(metrics.expectedRevenue)}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-neutral-500">Annual operating expenses</p><p className="text-xl font-bold mt-1">{formatNaira(metrics.annualOperatingExpenses)}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-neutral-500">Expected annual net cash flow</p><p className={`text-xl font-bold mt-1 ${metrics.netProfit >= 0 ? 'text-emerald-700' : 'text-red-600'}`}>{formatNaira(metrics.netProfit)}</p></div></div>
    {projection.error ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">Cash-flow projection failed: {projection.error}</p> : projection.loading || !months.length ? <section className="bg-white rounded-2xl border p-6 text-center text-neutral-500">Calculating the project cash-flow projection…</section> : <section className="bg-white rounded-2xl border p-5"><h3 className="font-bold">12-month cash-flow schedule</h3><p className="mt-1 text-xs text-neutral-500">The schedule starts in the calendar month you entered the workspace. M1 through M12 follow the farm’s operating timeline.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-neutral-500"><th className="py-2">Month</th><th className="py-2 text-right">Revenue</th><th className="py-2 text-right">Expenses</th><th className="py-2 text-right">Net cash flow</th><th className="py-2 text-right">Cumulative</th></tr></thead><tbody className="divide-y">{months.map(month => <tr key={month.monthIndex}><td className="py-2 font-semibold">M{month.monthIndex} · {month.monthName}{month.year ? ` ${month.year}` : ''}{month.harvest ? ' · Harvest' : ''}</td><td className="py-2 text-right">{formatNaira(month.revenue)}</td><td className="py-2 text-right">{formatNaira(month.expenses)}</td><td className={`py-2 text-right font-semibold ${month.netCashFlow >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{formatNaira(month.netCashFlow)}</td><td className={`py-2 text-right ${month.cumulativeCashFlow >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{formatNaira(month.cumulativeCashFlow)}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-neutral-500">Saved ROI cash-flow scenarios: {flows?.length ? `${flows.length} periods available` : 'none'}. They remain in the ROI report; this view shows the project’s monthly forecast.</p></section>}
  </div>;
};
